run_server: clustershell_server.c
	gcc clustershell_server.c -o clustershell_server.o
	./clustershell_server.o

run_client: clustershell_client.c
	gcc clustershell_client.c -o clustershell_client.o
	./clustershell_client.o
